# Generated by Django 4.0.5 on 2022-06-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0002_business_comment_profile_post_like_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
