# Generated by Django 4.0.5 on 2022-06-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0004_business_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
