# Generated by Django 4.0.5 on 2022-06-21 06:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outside', '0005_business_bio_neighborhood_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='images'),
        ),
    ]
